// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"

// ─────────────────────────────────────────────────────────────────────────────
// [T1]  makeNameRecord() — parses entire babyname.txt
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T1a: total record count is 4080", "[T1]")
{
    string state[N], gender[N], name[N];
    int year[N], count[N];
    int cnt = makeNameRecord(state, gender, year, name, count);
    REQUIRE(cnt == 4080);
}

TEST_CASE("T1b: first record fields are filled (IN/F/2011/Emma/453)", "[T1]")
{
    string state[N], gender[N], name[N];
    int year[N], count[N];
    int cnt = makeNameRecord(state, gender, year, name, count);
    REQUIRE(cnt > 0);
    REQUIRE(state[0] == "IN");
    REQUIRE(gender[0] == "F");
    REQUIRE(year[0] == 2011);
    REQUIRE(name[0] == "Emma");
    REQUIRE(count[0] == 453);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T2]  findNames() — basic match by state and starting character
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T2a: 'S' in CA returns 11 records", "[T2]")
{
    string state[N], gender[N], name[N];
    int year[N], count[N];
    int cnt = makeNameRecord(state, gender, year, name, count);
    int lines = findNames(cnt, state, gender, year, name, count, 'S', "CA");
    REQUIRE(lines == 11);
}

TEST_CASE("T2b: 'J' in TX returns 10 records", "[T2]")
{
    string state[N], gender[N], name[N];
    int year[N], count[N];
    int cnt = makeNameRecord(state, gender, year, name, count);
    int lines = findNames(cnt, state, gender, year, name, count, 'J', "TX");
    REQUIRE(lines == 10);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T3]  findNames() — additional state/letter combinations
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T3a: 'A' in CA returns 2 records", "[T3]")
{
    string state[N], gender[N], name[N];
    int year[N], count[N];
    int cnt = makeNameRecord(state, gender, year, name, count);
    int lines = findNames(cnt, state, gender, year, name, count, 'A', "CA");
    REQUIRE(lines == 2);
}

TEST_CASE("T3b: 'M' in NY returns 12 records", "[T3]")
{
    string state[N], gender[N], name[N];
    int year[N], count[N];
    int cnt = makeNameRecord(state, gender, year, name, count);
    int lines = findNames(cnt, state, gender, year, name, count, 'M', "NY");
    REQUIRE(lines == 12);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T4]  findNames() — edge cases (no match)
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T4a: nonexistent state 'XX' returns 0", "[T4]")
{
    string state[N], gender[N], name[N];
    int year[N], count[N];
    int cnt = makeNameRecord(state, gender, year, name, count);
    int lines = findNames(cnt, state, gender, year, name, count, 'A', "XX");
    REQUIRE(lines == 0);
}

TEST_CASE("T4b: starting char that no name begins with returns 0", "[T4]")
{
    string state[N], gender[N], name[N];
    int year[N], count[N];
    int cnt = makeNameRecord(state, gender, year, name, count);
    // '9' — names cannot start with a digit
    int lines = findNames(cnt, state, gender, year, name, count, '9', "CA");
    REQUIRE(lines == 0);
}
